namespace MedPra.Api.Services;

public static class DiseasePool
{
    public static readonly IReadOnlyDictionary<string, string[]> All =
        new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase)
    {
        ["Dahiliye"] = [
            "Tip 2 Diabetes Mellitus - Hipoglisemi atağı",
            "Tip 2 Diabetes Mellitus - Hiperglisemik hiperozmolar durum",
            "Demir eksikliği anemisi",
            "B12 eksikliği (Pernisiyöz anemi)",
            "Hemolitik anemi",
            "Hipertansiyon krizi (ensefalopati olmaksızın)",
            "Hipertansif acil (ensefalopati ile)",
            "Konjestif kalp yetmezliği - akut dekompansasyon",
            "KOAH akut atak",
            "Toplum kökenli pnömoni",
            "Pulmoner emboli",
            "Derin ven trombozu",
            "Akut böbrek hasarı (prerenal)",
            "Kronik böbrek hastalığı evre 4",
            "Nefrotik sendrom",
            "Akut viral hepatit B",
            "Alkolik karaciğer sirozu - asit",
            "Hepatik ensefalopati",
            "Primer biliyer kolanjit",
            "Hipertiroidizm (Graves hastalığı)",
            "Hipotiroidizm - Hashimoto tiroiditi",
            "Subakut tiroidit",
            "Primer hiperparatrioidizm - hiperkalsemi",
            "Addison hastalığı",
            "Cushing sendromu",
            "Feokromositoma",
            "Romatoid artrit - aktif hastalık",
            "Sistemik Lupus Eritematozus (SLE)",
            "Sjögren sendromu",
            "Sistemik skleroz",
            "Polimiyozit",
            "Gut artriti - akut atak",
            "Psödogut",
            "Ankilozan spondilit",
            "İnfektif endokardit",
            "Tüberküloz - akciğer",
            "HIV - başvuru semptomu",
            "Sepsis (ürosepsis)",
            "Multipl miyelom",
            "Non-Hodgkin lenfoma",
            "Kronik lenfositik lösemi",
            "Polisitemia vera",
            "Hiponatremi (SIADH)",
            "Hiperkalemi (böbrek yetmezliği zemininde)",
            "Laktik asidoz (metformin ilişkili)",
            "Warfarin ile aşırı antikoagülasyon - kanama",
            "Heparin kaynaklı trombositopeni (HIT)",
        ],

        ["Acil"] = [
            "STEMI - anterior miyokard enfarktüsü",
            "Aort diseksiyonu tip A",
            "Gerilim pnömotoraksı",
            "Anafilaksi - arı sokması",
            "Anafilaksi - ilaç reaksiyonu",
            "Status epileptikus",
            "İskemik inme - MCA tıkanması",
            "Spontan subaraknoid kanama",
            "Hipertansif ensefalopati",
            "Diabetik ketoasidoz",
            "Hipoglisemi - bilinç bozukluğu",
            "Sepsis - intraabdominal kaynak",
            "Septik şok",
            "Akut solunum yetmezliği",
            "Akut astım atağı - ağır",
            "Üst GİS kanaması - hematemez",
            "Akut apandisit",
            "Akut kolanjit",
            "Bağırsak obstrüksiyonu",
            "Mezenterik iskemi",
            "Dalak rüptürü - künt travma",
            "Epidural hematom - travma",
            "Subdural hematom - yaşlı hasta",
            "Crush sendromu - rabdomiyoliz",
            "Karbon monoksit zehirlenmesi",
            "Organofosfat zehirlenmesi",
            "Parasetamol zehirlenmesi",
            "Trisiklik antidepresan zehirlenmesi",
            "Hipotermi - dış ortam",
            "Isı çarpması",
            "Eklampsi",
            "Testis torsiyonu",
            "Priapizm",
            "Akut açı kapanma glokomu",
            "Peritonit - perforasyon",
        ],

        ["Kardiyoloji"] = [
            "STEMI - LAD tıkanması (anterior)",
            "STEMI - RCA tıkanması (inferior)",
            "NSTEMI",
            "Kararsız anjina",
            "Kronik stabil anjina - efor dispnesi",
            "Atriyal fibrilasyon - yeni başlangıç",
            "Atriyal fibrilasyon - hız kontrolü sorunu",
            "Paroksismal supraventriküler taşikardi (PSVT)",
            "Wolff-Parkinson-White sendromu",
            "Ventriküler taşikardi",
            "Tam kalp bloğu (3. derece AV blok)",
            "Sick sinus sendromu",
            "Dilate kardiyomiyopati",
            "Hipertrofik obstrüktif kardiyomiyopati (HKMP)",
            "Restriktif kardiyomiyopati",
            "Perikardit - akut",
            "Perikardiyal tamponad",
            "Konstriktif perikardit",
            "Miyokardit",
            "İnfektif endokardit - mitral kapak",
            "Romatizmal mitral darlık",
            "Mitral yetersizliği - akut",
            "Aort darlığı - ağır",
            "Aort yetersizliği - kronik",
            "Pulmoner hipertansiyon",
            "Kardiyojenik şok",
            "Akut dekompanse kalp yetmezliği",
            "Koroner arter hastalığı - çok damar",
            "Venöz tromboembolizm - DVT",
            "Pulmoner emboli - masif",
        ],

        ["Nöroloji"] = [
            "İskemik inme - MCA tıkanması (sol hemisfer)",
            "İskemik inme - laküner enfarkt",
            "Geçici iskemik atak (TİA)",
            "İntraserebral hemoraji - hipertansif",
            "Subaraknoid kanama - anevrizma",
            "Subdural hematom - kronik",
            "Epidural hematom",
            "Sinus ven trombozu",
            "Multipl skleroz - relaps",
            "Nöromyelitis optika (NMO)",
            "Guillain-Barré sendromu",
            "Myastenia Gravis - miyastenik kriz",
            "ALS (Amiyotrofik lateral skleroz) - erken",
            "Parkinson hastalığı - erken evre",
            "Parkinson hastalığı - motor dalgalanma",
            "Alzheimer demansı - orta evre",
            "Lewy cisimcikli demans",
            "Normal basınçlı hidrosefali",
            "Epilepsi - jeneralize tonik-klonik",
            "Epilepsi - temporal lob (fokal başlangıçlı)",
            "Status epileptikus - nonkonvülsif",
            "Bakteriyel menenjit",
            "Viral ensefalit (HSV)",
            "Tüberküloz menenjiti",
            "Beyin absesi",
            "Migren - komplike (hemiplejik)",
            "Küme baş ağrısı",
            "İdiyopatik intrakraniyal hipertansiyon",
            "Bell paralizisi",
            "Vestibüler nörit",
            "Meniere hastalığı",
            "Trigeminal nevralji",
            "Karpal tünel sendromu - ağır",
            "Diabetik polinöropati",
        ],

        ["Göğüs Hastalıkları"] = [
            "KOAH akut exaserbasyonu - ağır",
            "KOAH stabil - efor dispnesi",
            "Bronşiyal astım - akut atak",
            "Zor kontrollü astım",
            "Toplum kökenli pnömoni (CAP)",
            "Hastane kökenli pnömoni",
            "Aspirasyon pnömonisi",
            "Akciğer absesi",
            "Pulmoner tüberküloz - yeni tanı",
            "Tüberküloz plörezi",
            "Akciğer kanseri - adeno karsinom (bulgu/semptom)",
            "Küçük hücreli akciğer kanseri",
            "Mezotelyoma",
            "Spontan pnömotoraks - primer",
            "Spontan pnömotoraks - sekonder (KOAH zemininde)",
            "Plevral efüzyon - eksüda (tüberküloz)",
            "Plevral efüzyon - transüda (kalp yetmezliği)",
            "Pulmoner emboli - submassif",
            "İdiyopatik pulmoner fibrozis (IPF)",
            "Sarkoidoz - akciğer tutulumu",
            "Hipersensitivite pnömonisi",
            "Obstrüktif uyku apne sendromu",
            "Bronşiektazi",
            "Kistik fibrozis - erişkin",
            "Pnömokonyoz (silikozis)",
            "Pulmoner alveolar proteinozis",
        ],

        ["Gastroenteroloji"] = [
            "Peptik ülser hastalığı - duodenum ülseri",
            "Peptik ülser - kanayan mide ülseri",
            "H. pylori enfeksiyonu",
            "Gastroözofageal reflü (GÖRH) - erozyonlu özofajit",
            "Barrett özofagusu",
            "Özofagus varisi kanaması (siroz zemininde)",
            "Özofagus kanseri - semptomatik",
            "Mide kanseri - bulgu/semptom",
            "Akut pankreatit - biliyer",
            "Akut pankreatit - alkolik",
            "Kronik pankreatit - ağrı",
            "Pankreas kanseri - semptomatik",
            "Crohn hastalığı - alevlenme",
            "Ülseratif kolit - orta-ağır atak",
            "İrritabl bağırsak sendromu",
            "Çölyak hastalığı - malabsorpsiyon",
            "Kollajenöz kolit",
            "Kolorektal kanser - sol kolon",
            "Kolorektal kanser - sağ kolon (gizli kanama)",
            "İskemik kolit",
            "Psödomembranöz kolit (C. difficile)",
            "Kolelitiyazis - biliyer kolik",
            "Akut kolesistit - taşlı",
            "Kolanjit (Charcot üçlüsü)",
            "Primer sklerozan kolanjit",
            "Otoimmün hepatit",
            "Alkolik hepatit",
            "Non-alkolik yağlı karaciğer hepatiti (NASH)",
            "Karaciğer sirozu - hepatorenal sendrom",
            "Hepatosellüler karsinom",
            "Akut mezenterik iskemi",
            "Hernia inkarserata",
        ],

        ["Endokrinoloji"] = [
            "Tip 1 Diabetes Mellitus - yeni tanı",
            "Diabetik ketoasidoz",
            "Tip 2 DM - optimal kontrol sağlanamıyor",
            "Hipoglisemi - sulfonilurea ilişkili",
            "Graves hastalığı - hipertiroidizm",
            "Tiroid fırtınası",
            "Hashimoto tiroiditi - hipotiroidizm",
            "Miksödem koması",
            "Subakut (De Quervain) tiroidit",
            "Tiroid nodülü - malignite şüphesi",
            "Papiller tiroid kanseri",
            "Primer hiperparatrioidizm - asemptomatik hiperkalsemi",
            "Hiperparatiroidi - nefrolitiyazis",
            "Hipoparatiroidi - hipokalsemi",
            "Primer hiperaldosteronizm (Conn sendromu)",
            "Feokromositoma - hipertansif atak",
            "Cushing sendromu - pitüiter",
            "Cushing sendromu - adrenal",
            "Addison hastalığı - adrenal kriz",
            "Konjenital adrenal hiperplazi",
            "Akromegali",
            "Prolaktinoma",
            "Kraniyofarenjioma (hipopitüitarizm)",
            "Diabetes insipidus - santral",
            "SIADH - hiponatremi",
            "Osteoporoz - kırık riski yüksek",
            "Hipofosfatemi - rikets",
            "MEN tip 1",
            "MEN tip 2A",
            "İnsülinoma - hipoglisemi",
        ],

        ["Ortopedi"] = [
            "Proksimal femur kırığı - yaşlı hasta",
            "Kalça protezi çıkığı",
            "Femur cisim kırığı - genç yetişkin",
            "Tibial plato kırığı",
            "Patellar kırık - mekanizma",
            "Ayak bileği kırığı (Weber B)",
            "Distal radius kırığı (Colles)",
            "Skafoid kırığı - anatomik snuff box hassasiyeti",
            "Klavikula kırığı",
            "Proksimal humerus kırığı",
            "Omuz ön çıkığı (anterior dislokasyon)",
            "Rotator manşet yırtığı",
            "Biseps tendon yırtığı (proksimal)",
            "Lateral epikondilit (tenisçi dirseği)",
            "Medial epikondilit (golfçü dirseği)",
            "Karpal tünel sendromu",
            "De Quervain tendovajiniti",
            "Anterior çapraz bağ (ACL) yırtığı",
            "Medial menisküs yırtığı",
            "Diz osteoartriti - ağır",
            "Patellofemoral ağrı sendromu",
            "Aşil tendon yırtığı",
            "Plantar fasiit",
            "Lomber disk hernisi - S1 radikülopati",
            "Lomber spinal stenoz - nörojenik kladikasyo",
            "Servikal disk hernisi - C6 radikülopati",
            "Ankilozan spondilit - omurga tutulumu",
            "Septik artrit",
            "Osteomiyelit - hematojen",
            "Kompartman sendromu - tibia kırığı",
            "Kemik metastazı - patolojik kırık riski",
        ],

        ["Pediatri"] = [
            "Akut otitis media",
            "Akut gastroenterit - dehidrasyon",
            "Bronşiyolit (RSV)",
            "Krup sendromu (larengotrakeit)",
            "Febril konvülziyon",
            "Bakteriyel menenjit (meningokokal)",
            "Kawasaki hastalığı",
            "Henoch-Schönlein purpurası",
            "Akut romatizmal ateş",
            "Nefrotik sendrom - minimal değişiklik hastalığı",
            "İdiyopatik trombositopenik purpura (ITP)",
            "Tip 1 Diabetes Mellitus - yeni tanı (çocuk)",
            "Diabetik ketoasidoz (çocuk)",
            "Konjenital hipotiroidi",
            "Demir eksikliği anemisi (süt çocuğu)",
            "Beta talasemi majör",
            "G6PD eksikliği - hemolitik kriz",
            "Orak hücreli anemi - akut göğüs sendromu",
            "Akut lenfoblastik lösemi (ALL)",
            "Nöroblastom",
            "Wilms tümörü (nefroblastom)",
            "Çölyak hastalığı (çocuk)",
            "Hipertrofik pilor stenozu",
            "İntussüsepsiyon",
            "Meckel divertikülü - kanama",
            "Hirschsprung hastalığı",
            "Ventriküler septal defekt (VSD)",
            "Fallot tetralojisi",
            "Patent duktus arteriozus (PDA)",
            "Respiratuar distres sendromu (prematüre)",
            "Yenidoğan sarılığı - hemolitik",
            "Yenidoğan sepsisi",
            "Febril nötropeni (çocuk)",
            "Akut apandisit (çocuk)",
        ],

        ["Kadın Doğum"] = [
            "Ektopik gebelik - tubal rüptür",
            "Abortus imminens (düşük tehdidi)",
            "Plasenta previa - kanama",
            "Ablasyo plasenta",
            "Preeklampsi - ağır",
            "Eklampsi",
            "HELLP sendromu",
            "Gestasyonel diabetes mellitus",
            "Hiperemezis gravidarum",
            "Servikal yetmezlik",
            "Postpartum kanama - atoni",
            "Postpartum endometrit",
            "Over kisti torsiyonu",
            "Over kisti rüptürü",
            "Miyom uteri - semptomatik",
            "Endometriozis - kronik pelvik ağrı",
            "Pelvik inflamatuvar hastalık (PID)",
            "Tubo-ovarian abse",
            "Serviks kanseri - erken evre",
            "Endometrium kanseri",
            "Over kanseri - ileri evre",
            "Hidatidiform mol",
            "Gestasyonel trofoblastik neoplazi",
            "Polikistik over sendromu (PKOS)",
            "Primer dismenore",
            "Sekonder dismenore (endometriozis)",
            "Premenstürel sendrom / PMDD",
            "Menopoz - vazomotor semptomlar",
            "Stres üriner inkontinans",
            "Vajinal kandidiyazis",
            "Bakteriyel vajinozis",
            "Bartolin bezi absesi",
            "Servikal polip - kanama",
        ],
    };

}
